name: Allure test report
description: Create Github Pages hosted allure report

inputs:
  github-key:
    description: 'Github token'
    required: true
  test-type:
    description: 'Integration or unit'
    default: 'unit'
    required: false
  allure-dir:
    description: 'Directory where allure report lives'
    default: 'allure-results'
    required: false
  pages-branch:
    description: 'Github Pages branch'
    default: 'gh-pages'
    required: false

runs:
  using: "composite"
  steps:
    - name: Get repo name for URL
      shell: bash
      run: |
        echo "GH_REPO=${GITHUB_REPOSITORY#*/}" >> "$GITHUB_ENV"
        
    - name: Run Allure action
      uses: simple-elf/allure-report-action@v1.6
      with:
        allure_results: ${{ inputs.allure-dir }}
        allure_history: allure-history
        subfolder: ${{ github.event.pull_request.head.sha  || github.sha }}_${{ inputs.test-type }}
        keep_reports: 20

    - name: Deploy report to Github Pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ inputs.github-key }}
        PUBLISH_BRANCH: ${{ inputs.pages-branch }}
        PUBLISH_DIR: allure-history
        
    - name: Post the link to the report
      if: always()
      uses: Sibz/github-status-action@v1
      with:
          authToken: ${{ inputs.github-key }}
          context: ${{ inputs.test-type }} test result
          state: ${{ job.status }}
          sha: ${{ github.event.pull_request.head.sha  || github.sha }}
          target_url: https://docs.firebolt.io/${{ env.GH_REPO }}/${{ github.event.pull_request.head.sha  || github.sha }}_${{ inputs.test-type }}
