name: Allure test report
description: Create Github Pages hosted allure reports

inputs:
  github-token:
    description: 'Github token'
    required: true
  mapping-json:
    description: 'Mapping of source where allure test results were written and unique, URL friendly description'
    required: true
    # Example:
    # {
    #   "allure-results": "core",
    #   "allure-results-https": "core_https"
    # }
  allure-version:
    description: 'Version of Allure to be installed'
    required: false
    default: '2.38.1'
  pages-branch:
    description: 'Github Pages branch'
    default: 'gh-pages'
    required: false
  report-path:
    description: 'Path under which the report will be published. Defaults to allure/<repo-name>_<sha>'
    required: false

runs:
  using: "composite"
  steps:
      # Need to pull the pages branch in order to fetch the previous runs
      - name: Get Allure history
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: always()
        continue-on-error: true
        with:
          ref: ${{ inputs.pages-branch }}
          path: ${{ inputs.pages-branch }}
          persist-credentials: false

      - name: Install Allure CLI
        id: install-allure
        if: always()
        env:
          ALLURE_VERSION: ${{ inputs.allure-version }}
        shell: bash
        run: |
          npm install -g allure-commandline@${ALLURE_VERSION}

      - name: Get repo gh-pages URL
        id: get_repo_vars
        env:
          GH_TOKEN: ${{ inputs.github-token }}
          PROVIDED_REPORT_PATH: ${{ inputs.report-path }}
        shell: bash
        run: ${{ github.action_path }}/scripts/get-repo-vars.sh

      - name: Generate All Reports Locally
        id: generate-reports
        if: always() && steps.install-allure.outcome == 'success'
        env:
          # Where to write allure reports
          REPORT_DEST_BASE: "allure-final/${{ steps.get_repo_vars.outputs.report_path }}"
          # From where allure reports are served
          REPORT_URL_BASE: "${{ steps.get_repo_vars.outputs.repo_url }}${{ steps.get_repo_vars.outputs.report_path }}"
          MAPPING_JSON: ${{ inputs.mapping-json }}
        shell: bash
        run: ${{ github.action_path }}/scripts/generate-reports.sh

      - name: Deploy all reports to GitHub Pages
        id: deploy-reports
        shell: bash
        env:
          PAGES_BRANCH: ${{ inputs.pages-branch }}
          REPORT_FOLDER: ./allure-final
          MAX_ATTEMPTS: 5
          GH_TOKEN: ${{ inputs.github-token }}
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: ${{ github.action_path }}/scripts/deploy-reports.sh

      - name: Update PR Status
        if: always()
        env:
          GH_TOKEN: ${{ inputs.github-token }}
          URLS_JSON: ${{ steps.generate-reports.outputs.urls || '{}'}}
          JOB_STATUS: ${{ job.status }}
          API_URL: "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha || github.sha }}"
        shell: bash
        run: ${{ github.action_path }}/scripts/update-pr-status.sh

      - name: Set Job Summary
        if: always() && steps.deploy-reports.outcome == 'success'
        env:
          URLS_JSON: ${{ steps.generate-reports.outputs.urls || '{}'}}
        shell: bash
        run: ${{ github.action_path }}/scripts/set-job-summary.sh
