name: Allure test report
description: Create Github Pages hosted allure reports

inputs:
  github-token:
    description: 'Github token'
    required: true
  mapping-json:
    description: 'Mapping of source where allure test results were written and unique, URL friendly description'
    required: true
    # Example:
    # {
    #   "allure-results": "core",
    #   "allure-results-https": "core_https"
    # }
  allure-version:
    description: 'Version of Allure to be installed'
    required: false
    default: '2.38.1'
  pages-branch:
    description: 'Github Pages branch'
    default: 'gh-pages'
    required: false
  report-path:
    description: 'Path under which the report will be published. Defaults to allure/<repo-name>_<sha>'
    required: false

runs:
  using: "composite"
  steps:
      # Need to pull the pages branch in order to fetch the previous runs
      - name: Get Allure history
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: always()
        continue-on-error: true
        with:
          ref: ${{ inputs.pages-branch }}
          path: ${{ inputs.pages-branch }}
          persist-credentials: false

      - name: Install Allure CLI
        id: install-allure
        if: always()
        env:
          ALLURE_VERSION: ${{ inputs.allure-version }}
        shell: bash
        run: |
          npm install -g allure-commandline@${ALLURE_VERSION}

      - name: Get repo gh-pages URL
        id: get_repo_vars
        env:
          GH_TOKEN: ${{ inputs.github-token }}
          GITHUB_SHA: ${{ github.sha }}
          PROVIDED_REPORT_PATH: ${{ inputs.report-path }}
        shell: bash
        run: |
          base_url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
          repository_name=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
          echo "repo_url=${base_url}" >> "$GITHUB_OUTPUT"
          echo "repo_name=${repository_name}" >> "$GITHUB_OUTPUT"

          if [ -z "${PROVIDED_REPORT_PATH}" ]; then
            echo "report_path=allure/${repository_name}_${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          else
            echo "report_path=${PROVIDED_REPORT_PATH}" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate All Reports Locally
        id: generate-reports
        if: always() && steps.install-allure.outcome == 'success'
        env:
          # Where to write allure reports
          REPORT_DEST_BASE: "allure-final/${{ steps.get_repo_vars.outputs.report_path }}"
          # From where allure reports are served
          REPORT_URL_BASE: "${{ steps.get_repo_vars.outputs.repo_url }}${{ steps.get_repo_vars.outputs.report_path }}"
          MAPPING_JSON: ${{ inputs.mapping-json }}
        shell: bash
        run: |
          # Create a temp file to store URLs
          echo "{}" > urls.json

          echo "$MAPPING_JSON" | jq -r 'to_entries | .[] | "\(.key) \(.value)"' | while read -r src suffix; do
            if [ -d "$src" ]; then
              echo "Generating report: $src -> ${REPORT_DEST_BASE}_${suffix}"
              allure generate "$src" -o "${REPORT_DEST_BASE}_${suffix}"

              # Build URL and update the temp JSON file
              FINAL_URL="${REPORT_URL_BASE}_${suffix}"
              jq --arg k "$suffix" --arg v "$FINAL_URL" '. + {($k): $v}' urls.json > urls.tmp && mv urls.tmp urls.json
            else
              echo "⚠️ Skipping: Directory '$src' not found."
            fi
          done
          echo "urls=$(cat urls.json | jq -c .)" >> $GITHUB_OUTPUT

      - name: Deploy all reports to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        id: deploy-reports
        if: always() && steps.generate-reports.outcome == 'success' && steps.generate-reports.outputs.urls != '{}'
        with:
          attempt-limit: 3
          branch: ${{ inputs.pages-branch }}
          folder: ./allure-final
          force: false

      - name: Update PR Status
        if: always()
        env:
          GH_TOKEN: ${{ inputs.github-token }}
          URLS_JSON: ${{ steps.generate-reports.outputs.urls || '{}'}}
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          JOB_STATUS: ${{ job.status }}
          API_URL: "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha || github.sha }}"
        shell: bash
        run: |
          # Map job status to GitHub Status API state
          case "${JOB_STATUS}" in
            success) STATE="success" ;;
            failure) STATE="failure" ;;
            cancelled) STATE="error" ;;
            *) STATE="error" ;;
          esac

          # Parse the JSON output and loop through each name/url pair
          echo "$URLS_JSON" | jq -r 'to_entries | .[] | "\(.key) \(.value)"' | while read -r name url; do
            echo "Setting status for $name..."

            curl -fsSL \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "$API_URL" \
              -d "{
                \"state\": \"$STATE\",
                \"target_url\": \"$url\",
                \"description\": \"Click to access Allure report\",
                \"context\": \"Test Results ($name)\"
              }"
          done

      - name: Set Job Summary
        if: always() && steps.deploy-reports.outcome == 'success'
        env:
          URLS_JSON: ${{ steps.generate-reports.outputs.urls || '{}'}}
        shell: bash
        run: |
          echo "### Test Reports" >> $GITHUB_STEP_SUMMARY
          echo "$URLS_JSON" | jq -r 'to_entries | .[] | "\(.key) \(.value)"' | while read -r name url; do
            echo "* [Report: $name]($url)" >> $GITHUB_STEP_SUMMARY
          done
