name: Move Major Release Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'vX.Y.Z'
        type: string
        required: true
  release:
    types: [created]

jobs:
  movetag:
    runs-on: ubuntu-slim
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Get major version num and update tag
      shell: bash
      env:
        PROVIDED_TAG: ${{ inputs.tag }}
      run: |
        if [ ! -z ${PROVIDED_TAG} ]; then
          VERSION=${PROVIDED_TAG}
        else
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        echo "Using version ${VERSION}"
        MAJOR=${VERSION%%.*}
        git config --global user.name 'Release Bot'
        git config --global user.email 'release-bot@firebolt.io'
        git tag -fa ${MAJOR} -m "Update major version tag"
        git push origin ${MAJOR} --force
